stages:
  - build
  - mirror

build:
  image: node
  stage: build
  script:
    - npm install --quiet
    - ./build_5.0-5.4_range.sh
  artifacts:
    paths:
      - artifact/*.zip

mirror:github:
  image: debian
  stage: mirror
  script:
    - apt-get update && apt-get install -y git
    - git clone --mirror https://git.bitsensor.io/front-end/elastalert-kibana-plugin.git mirror-github
    - cd mirror-github
    - git remote add github https://$MIRROR_GITHUB_USER:$MIRROR_GITHUB_PASSWORD@$MIRROR_GITHUB_URL
    - git push -u github -q --mirror
  when: always
