stages:
  - build
  - mirror

build:
  image: node:alpine
  stage: build
  script:
    - apk --update --no-cache add python
    - npm install --quiet
    - npm run build --quiet
    - mkdir artifact
    - cp build/elastalert-kibana-plugin-*.zip artifact/elastalert-kibana-plugin-latest.zip
  artifacts:
    paths:
      - artifact/elastalert-kibana-plugin-latest.zip

mirror:github:
  image: alpine:latest
  stage: mirror
  script:
    - apk --update --no-cache add git
    - git clone --mirror https://git.bitsensor.io/front-end/elastalert-kibana-plugin.git mirror-github
    - cd mirror-github
    - git remote add github https://$MIRROR_GITHUB_USER:$MIRROR_GITHUB_PASSWORD@$MIRROR_GITHUB_URL
    - git push -u github -q --mirror
  when: always
