stages:
  - build

build:
  image: node:alpine
  stage: build
  script:
    - apk --update --no-cache add python make gcc g++
    - npm install --quiet
    - npm run build --quiet
    - mkdir artifact
    - cp build/elastalert-kibana-plugin-*.zip artifact/elastalert-kibana-plugin-latest.zip
  artifacts:
    paths:
      - artifact/elastalert-kibana-plugin-latest.zip
